name: flutter_protected_work
description: Protect your work against greedy clients.
version: 1.0.1
homepage: https://github.com/f-person/flutter_protected_work

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
